### ISSUE TITLE
Compiling Water Meter

### ISSUE THREAD

**Issue by aleonnet** [skx/esp8266#6]
Hi Steve @skx 
First of all thank you for the great projects!
I'm using D1 mini Pro and I'm new to ESP8266. I just can't figure out what's gone wrong when I try to compile the code.
How to correct it?

--------------------------
Arduino: 1.8.2 (Mac OS X), Board: "WeMos D1 R2 & mini, 80 MHz, 115200, 4M (3M SPIFFS)"

/Users/alessandro/Documents/Arduino/esp8266-master/d1-water-meter/d1-water-meter.ino: In function 'void setup()':
d1-water-meter:91: error: invalid user-defined conversion from 'IPAddress' to 'const char*' [-fpermissive]
     DEBUG_LOG(WiFi.localIP());
                             ^
In file included from /Users/alessandro/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/ESP8266WiFi.h:31:0,
                 from /Users/alessandro/Documents/Arduino/esp8266-master/d1-water-meter/d1-water-meter.ino:1:
/Users/alessandro/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/IPAddress.h:56:9: note: candidate is: IPAddress::operator uint32_t() const <near match>
         operator uint32_t() const {
         ^
/Users/alessandro/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/IPAddress.h:56:9: note:   no known conversion for implicit 'this' parameter from 'uint32_t {aka unsigned int}' to 'const char*'
exit status 1
invalid user-defined conversion from 'IPAddress' to 'const char*' [-fpermissive]

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by skx** [comment]
That project is still using my older build so I've not updated it recently.

I think this should fix it though:   Change line 91 from this:

       DEBUG_LOG(WiFi.localIP());

To this:

       DEBUG_LOG(WiFi.localIP().toString());

**Comment by skx** [comment]
Or possibly even:

            DEBUG_LOG(WiFi.localIP().toString().c_str());

**Comment by aleonnet** [comment]
Thanks, I had tried your first suggestion before and it didn't work.
I'll try the second one later today.


Em sex, 14 de jul de 2017 às 01:13, Steve Kemp <notifications@github.com>
escreveu:

**Comment by skx** [comment]
I should update this project to use the newer debug-library, will do that over the weekend.

Let me know anyway :)

**Comment by aleonnet** [comment]
Great news! If you allow me to suggest a killer improvement, It would be
great to show the current and acc measurements on the oled with a push a of
button :)
I'm planning to integrate it to my node-red dashboard with the mqtt
mosquitto server and store the results in a sqlite db.
I already do that with power measurements of sonoff pow

Em sex, 14 de jul de 2017 às 01:27, Steve Kemp <notifications@github.com>
escreveu:

**Comment by skx** [comment]
Pushed a commit which I think should resolve the problem now.

As for your idea with OLED it sounds like a neat idea, but I think outside the scope of this particular example.  As you know it just sends water-data to the central MQ bus, so  there most likely isn't even going to be a display present - well not for me at least.  If you want to update the code to do other things though that's gonna be fun I'm sure :)

**Comment by aleonnet** [comment]
@skx Steve, It still not compiling 100%. I tried unsucessfully use the conversion .toString() or .c_str() or .toString.c_str(). I don't know how to solve it.

Arduino: 1.8.2 (Mac OS X), Board: "WeMos D1 R2 & mini, 80 MHz, 115200, 4M (3M SPIFFS)"

/Users/alessandro/Documents/Arduino/esp8266-master/d1-water-meter/d1-water-meter.ino: In function 'void reconnect()':
d1-water-meter:286: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
             DEBUG_LOG(client.state());
                                    ^
In file included from /Users/alessandro/Documents/Arduino/esp8266-master/d1-water-meter/d1-water-meter.ino:13:0:
debug.h:11: error: initializing argument 1 of 'void DEBUG_LOG(const char*, ...)' [-fpermissive]
 void DEBUG_LOG(const char *format, ...)
      ^
exit status 1
invalid conversion from 'int' to 'const char*' [-fpermissive]

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by skx** [comment]
Did these two commits help?

* https://github.com/skx/esp8266/commit/7c202e39300c037c55b35f338d54f9f56963b8cd
* https://github.com/skx/esp8266/commit/77451b1cf5c4ca9d10e0348c8b2e0815d138710c

**Comment by aleonnet** [comment]
Yes! Thank you Steve. Now it compiles 100%.

**Comment by skx** [comment]
Great news.

FWIW I'm using Arduino 1.8.0 and it always did.  I'll close this now anyway, thanks for your patience :)

**Comment by aleonnet** [comment]
Thanks for your patience as well and great help and support!
It's really hard to understand these kind of errors and how difficult it is
to figure out a simple type conversion.
I use python and JS and its so easy.
Anyway, it worked!

Em sáb, 15 de jul de 2017 às 00:16, Steve Kemp <notifications@github.com>
escreveu:

**Comment by aleonnet** [comment]
https://youtu.be/O2pNShqB21o

Hi Steve, this is my version of the water flow meter.
The flow measurement is still being simulated as I haven't the flow sensor
ready yet.
Thanks!


Em sáb, 15 de jul de 2017 às 08:58, Alessandro Barbosa <
barbosa.alessandro@gmail.com> escreveu:

**Comment by skx** [comment]
Looks very nice, thanks for sharing :)
